DELETE FROM USER_AUTH;
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Rudvij','rudvijn','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Rachit','rachitd','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Sakshi','sakshid','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Pranav','pranavm','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Shreyas','shreyasp','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Anshuman','anshumanp','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Rohit','rohit','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Sunny','sunny','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Kaushal','kaushal','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Pankaj','pankaj','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Ruchika','ruchika','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Raghav','raghav','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Rahul','rahul','test');
INSERT INTO USER_AUTH (NAME,USER_NAME,PASSWORD) VALUES ('Priyanka','priyankam','test');

--DELETE FROM RESTAURANT;
INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME,USER_ID) VALUES ('Carpe Diem','10:00:00','23:00:00',2);
INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME,USER_ID) VALUES ('Bar B Q','09:00:00','22:30:00',3);
INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME,USER_ID) VALUES ('Rang De Basanti Dhaba','09:30:00','22:00:00',4);
INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME,USER_ID) VALUES ('Raasta Cafe','09:00:00','23:30:00',5);
--INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME) VALUES ('Dominos','10:00:00','10:00:00');
--INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME) VALUES ('Pizza Hut','10:00:00','10:00:00');
--INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME) VALUES ('Burma Burma','10:00:00','10:00:00');
--INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME) VALUES ('Aaji Sai','10:00:00','10:00:00');
--INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME) VALUES ('Casa Kitchen','10:00:00','10:00:00');
--INSERT INTO RESTAURANT (NAME,START_TIME,END_TIME) VALUES ('Aafra Deli','10:00:00','10:00:00');

--CART CANNOT BE MORE THAN NO OF USERS, ##ONE USER ONE CART
DELETE FROM CART;
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (821.21,5,1);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (829,6,2);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (855,7,1);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (1022.11,8,2);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (628.00,9,3);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (1242,10,4);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (342,11,4);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (222,12,3);
INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (444,13,2);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (899,7,1);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (1022.11,8,2);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (628.00,9,3);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (1242,10,4);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (342,11,4);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (222,12,3);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (444,13,2);
--INSERT INTO CART (TOTAL_PRICE,USER_ID,RESTAURANT_ID) VALUES (444,14,2);

DELETE FROM ADDRESS;
--DIFFERENT AREA'S RESTAURANT AND NEARBY PEOPLE
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('12 B Russel Street','India','West Bengal','Kolkata','700071',22.55250375576387, 88.3523521241455,1,NULL);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('5 B Park Street','India','West Bengal','Kolkata','700071',22.55335817115387, 88.35266287996735,2,NULL);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('19 Middleton Row','India','West Bengal','Kolkata','700071',22.550137928239852, 88.34926183903318,3,NULL);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('139 Canning Street','India','West Bengal','Kolkata','700071',22.548612002297017, 88.35374649233024,NULL,6);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('138 Canning Street','India','West Bengal','Kolkata','700071',22.548612002297016, 88.35374649233023,NULL,7);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('18 Bara Bazar','India','West Bengal','Kolkata','700071',22.550871159378758, 88.35381086534407,NULL,8);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('20 NS Road','India','West Bengal','Kolkata','700071',22.548661545570845, 88.35117157176131,NULL,9);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('56 M G Road','India','West Bengal','Kolkata','700071',22.546293355212573, 88.35048492628042,NULL,10);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('33 Park Circus','India','West Bengal','Kolkata','700071', 22.54928578980302, 88.35807021322184,NULL,11);
--DIFFERENT AREA'S RESTAURANT AND NEARBY PEOPLE
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('8 Lake Town','India','West Bengal','Kolkata','700016',22.555320005369822, 88.36386378473019,4,NULL);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('10 Bangur Avneue','India','West Bengal','Kolkata','700016',22.560550998685194, 88.36286871509233,NULL,12);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('18 VIP Road','India','West Bengal','Kolkata','700016',22.558391079761858, 88.36242883271377,NULL,13);
INSERT INTO ADDRESS (ADDRESS_LINE,COUNTRY,STATE,CITY,PINCODE,LATITUDE,LONGITUDE,RESTAURANT_ID,USER_ID) VALUES ('15 Space Circle','India','West Bengal','Kolkata','700016',22.557489452230325, 88.36361973346969,NULL,14);

DELETE FROM FOOD_ITEM;
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Butter Naan','Tasty Naan filled with Butter',true,'NORTH_INDIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Pizza','Very Cheesy Pizza',true,'ITALIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Penne Pasta','Tasty Pasta',true,'ITALIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Omelete','Egg Omelete',false,'NORTH_INDIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Egg Bhurji','Smashed Eggs',false,'NORTH_INDIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Vada Pao','Bun and Aloo patty',true,'MAHARASHTRIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Misal Pav','Bun and Mixture',true,'MAHARASHTRIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Hakka Noodles','Slimy Noodles',true,'CHINESE');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Machurian','Gravy Gobhi Machurian',true,'CHINESE');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Idli','Buttery Soft Idli',true,'SOUTH_INDIAN');
INSERT INTO FOOD_ITEM (NAME,DESCRIPTION,IS_VEG,CUISINE) VALUES ('Dosa','Paper Thin Dosa',true,'SOUTH_INDIAN');

DELETE FROM CONTACT_INFO;
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111111','pranavm@gmail.com',1,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111110','rudvejn@gmail.com',2,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111112','shreyasp@gmail.com',3,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111113','anshumanp@gmail.com',4,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111114','rachitd@gmail.com',5,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111115','sakshid@gmail.com',6,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111116','rohitk@gmail.com',7,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111117','sunnys@gmail.com',8,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111118','kaushalk@gmail.com',9,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('911111119','pankajc@gmail.com',10,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222220','ruchikad@gmail.com',11,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222221','raghavm@gmail.com',12,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222222','rahulm@gmail.com',13,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222223','priyankam@gmail.com',14,NULL);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222224','carped@gmail.com',NULL,1);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222225','barbq@gmail.com',NULL,2);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222226','rdbd@gmail.com',NULL,3);
INSERT INTO CONTACT_INFO (PHONE_NUMBER,EMAIL,USER_ID,RESTAURANT_ID) VALUES ('922222227','raastac@gmail.com',NULL,4);

DELETE FROM CONSUMER_ORDER;
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1000,'ORDER_PLACED',6,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1100,'ORDER_PLACED',6,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1200,'ORDER_PLACED',7,2);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1300,'ORDER_PLACED',7,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1400,'ORDER_PLACED',8,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1500,'RESTAURANT_ACCEPTED',8,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1600,'RESTAURANT_ACCEPTED',12,2);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1700,'RESTAURANT_ACCEPTED',11,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1800,'RESTAURANT_ACCEPTED',9,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (1900,'RESTAURANT_ACCEPTED',9,3);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2000,'FOOD_PREPARED',9,4);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2100,'FOOD_PREPARED',10,4);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2200,'FOOD_PREPARED',11,3);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2300,'FOOD_PREPARED',12,4);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2400,'FOOD_PICKED_UP',13,3);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2500,'FOOD_PICKED_UP',14,4);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2600,'FOOD_PICKED_UP',9,1);
INSERT INTO CONSUMER_ORDER (TOTAL_PRICE,ORDER_STATUS,USER_ID,RESTAURANT_ID) VALUES (2700,'FOOD_PICKED_UP',12,2);


DELETE FROM ORDER_ITEM;
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,5,1,1);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,5,2,1);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (300,5,3,1);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,5,4,1);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,1,8,2);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,1,9,2);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,2,11,3);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,2,5,3);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (300,2,1,3);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,2,6,4);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,2,7,4);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (300,2,8,4);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,3,1,5);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,3,2,5);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (300,3,3,5);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,1,1,6);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,1,2,6);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (300,1,3,6);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,1,5,6);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,2,1,7);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,2,2,7);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (100,2,9,8);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (200,2,10,8);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (220,3,9,9);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (220,3,10,9);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (390,1,10,10);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,2,11,11);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,2,10,12);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,2,9,12);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,2,1,13);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,2,2,14);
INSERT INTO ORDER_ITEM (PRICE,QUANTITY,FOOD_ITEM_ID,ORDER_ID) VALUES (400,2,5,15);


--RESTAURANT_ID HAS BE SAME IN CART AND RESTAUARNT_ITEM RESPECTIVELY
DELETE FROM RESTAURANT_ITEM;
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (3,300,true,1,1,1);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (4,400,true,2,1,NULL);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (5,450,true,3,1,1);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (3,250,true,4,1,NULL);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (5,200,true,5,1,1);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (4,350,true,6,2,NULL);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (3,220,true,7,2,2);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (4,300,true,8,2,7);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (2,400,true,9,2,2);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (1,450,true,10,2,7);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (5,550,true,11,3,NULL);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (3,300,true,1,3,6);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (4,400,true,2,3,6);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (5,450,true,3,3,NULL);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (3,250,true,4,3,3);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (5,200,true,5,3,3);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (4,350,true,6,4,4);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (3,220,true,7,4,5);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (4,300,true,8,4,NULL);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (2,400,true,9,4,5);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (1,450,true,10,4,NULL);
INSERT INTO RESTAURANT_ITEM (RATING,PRICE,IS_AVAILABLE,FOOD_ITEM_ID,RESTAURANT_ID,CART_ID) VALUES (5,550,true,11,4,4);


DELETE FROM CART_ITEM;
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (2,1,1);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,3,1);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (2,5,1);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,7,2);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (2,20,7);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (3,9,2);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,19,7);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (2,22,6);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,17,6);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (2,1,3);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,5,3);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (2,6,4);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,11,5);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (3,15,5);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,9,4);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,13,8);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,14,8);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,9,9);
INSERT INTO CART_ITEM (QUANTITY,RESTAURANT_ITEM_ID,CART_ID) VALUES (1,10,9);


--Auth Tables

INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.CREATE');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.UPDATE');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.DELETE');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.VIEW');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.LIST');

INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.TIMING.UPDATE');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.ITEMS.UPDATE');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.ITEMS.CREATE');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.ITEMS.DELETE');
INSERT INTO PRIVILEGES (NAME) VALUES ('RESTAURANT.ITEMS.PERSONALIZE');

INSERT INTO PRIVILEGES (NAME) VALUES ('ORDER.STATUS.UPDATE');
INSERT INTO PRIVILEGES (NAME) VALUES ('ORDER.CREATE');
INSERT INTO PRIVILEGES (NAME) VALUES ('ORDER.STATUS');
INSERT INTO PRIVILEGES (NAME) VALUES ('ORDER.LIST');

INSERT INTO ROLES (NAME) VALUES ('CUSTOMER');
INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('RESTAURANT_OWNER');

INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='CUSTOMER', SELECT ID FROM PRIVILEGES WHERE NAME='ORDER.STATUS');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='CUSTOMER', SELECT ID FROM PRIVILEGES WHERE NAME='ORDER.CREATE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='CUSTOMER', SELECT ID FROM PRIVILEGES WHERE NAME='ORDER.LIST');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='CUSTOMER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.VIEW');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='CUSTOMER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.LIST');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='CUSTOMER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.ITEMS.PERSONALIZE');

INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='ADMIN', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.CREATE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='ADMIN', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.UPDATE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='ADMIN', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.DELETE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='ADMIN', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.VIEW');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='ADMIN', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.LIST');

INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.TIMING.UPDATE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.ITEMS.CREATE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.ITEMS.UPDATE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.ITEMS.DELETE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='RESTAURANT.VIEW');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='ORDER.STATUS.UPDATE');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='ORDER.LIST');
INSERT INTO ROLE_PRIVILEGES VALUES (SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER', SELECT ID FROM PRIVILEGES WHERE NAME='ORDER.STATUS');


INSERT INTO USER_ROLES VALUES (1, SELECT ID FROM ROLES WHERE NAME='ADMIN');

INSERT INTO USER_ROLES VALUES (2, SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER');
INSERT INTO USER_ROLES VALUES (3, SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER');
INSERT INTO USER_ROLES VALUES (4, SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER');
INSERT INTO USER_ROLES VALUES (5, SELECT ID FROM ROLES WHERE NAME='RESTAURANT_OWNER');

INSERT INTO USER_ROLES VALUES (6, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (7, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (8, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (9, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (10, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (11, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (12, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (13, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
INSERT INTO USER_ROLES VALUES (14, SELECT ID FROM ROLES WHERE NAME='CUSTOMER');
