DROP ALL OBJECTS;
CREATE TABLE IF NOT EXISTS USER_AUTH (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	NAME VARCHAR(50) ,  
	USER_NAME VARCHAR(50) ,
	PASSWORD VARCHAR(512)
);
CREATE TABLE IF NOT EXISTS RESTAURANT (
	ID INT AUTO_INCREMENT PRIMARY KEY,  
	NAME VARCHAR(50) ,  
	START_TIME TIME ,
	END_TIME TIME,
	USER_ID INT
);
CREATE TABLE IF NOT EXISTS FOOD_ITEM (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	NAME VARCHAR(50) ,  
	DESCRIPTION VARCHAR(100) ,
	IS_VEG BOOLEAN ,
	CUISINE VARCHAR(50) 
);
CREATE TABLE IF NOT EXISTS CART (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	TOTAL_PRICE FLOAT ,  
	USER_ID INT ,
	RESTAURANT_ID INT 
);
CREATE TABLE IF NOT EXISTS ADDRESS (
	ID INT AUTO_INCREMENT  PRIMARY KEY,
	ADDRESS_LINE VARCHAR (100),
	COUNTRY VARCHAR(50) ,  
	STATE VARCHAR(50) ,
	CITY VARCHAR(50) ,
	PINCODE VARCHAR(10) ,
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	RESTAURANT_ID INT,
	USER_ID INT
);
CREATE TABLE IF NOT EXISTS RESTAURANT_ITEM (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	RATING INT ,
	PRICE FLOAT ,  
	IS_AVAILABLE BOOLEAN,
	FOOD_ITEM_ID INT,
	RESTAURANT_ID INT,
	CART_ID INT
);
CREATE TABLE IF NOT EXISTS CART_ITEM (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	QUANTITY INT ,  
	RESTAURANT_ITEM_ID INT ,
	CART_ID INT 
);
CREATE TABLE IF NOT EXISTS CONTACT_INFO (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	PHONE_NUMBER VARCHAR(20) ,  
	EMAIL VARCHAR(100) ,
	USER_ID INT ,
	RESTAURANT_ID INT 
);
CREATE TABLE IF NOT EXISTS CONSUMER_ORDER (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	TOTAL_PRICE FLOAT ,  
	ORDER_STATUS VARCHAR(50) ,
	USER_ID INT ,
	RESTAURANT_ID INT 
);
CREATE TABLE IF NOT EXISTS ORDER_ITEM (
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	PRICE FLOAT ,  
	QUANTITY INT ,
	FOOD_ITEM_ID INT,
	ORDER_ID INT
);

--RESTAURANT Foreign Keys With USER
ALTER TABLE RESTAURANT
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES USER_AUTH(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;

--ADDRESS Foreign Keys With RESTAURANT and USER_AUTH
ALTER TABLE ADDRESS
	ADD FOREIGN KEY (RESTAURANT_ID) 
	REFERENCES RESTAURANT(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;
ALTER TABLE ADDRESS
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES USER_AUTH(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;

--CART Foreign Keys With RESTAURANT and USER_AUTH
ALTER TABLE CART
	ADD FOREIGN KEY (RESTAURANT_ID) 
	REFERENCES RESTAURANT(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;
ALTER TABLE CART
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES USER_AUTH(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;
	
--CART_ITEM Foreign Keys With RESTAURANT and USER_AUTH
ALTER TABLE CART_ITEM
	ADD FOREIGN KEY (CART_ID) 
	REFERENCES CART(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;
ALTER TABLE CART_ITEM
	ADD FOREIGN KEY (RESTAURANT_ITEM_ID)
	REFERENCES RESTAURANT_ITEM(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;
	
--CONTACT_INFO Foreign Keys With RESTAURANT and USER_AUTH
ALTER TABLE CONTACT_INFO
	ADD FOREIGN KEY (RESTAURANT_ID) 
	REFERENCES RESTAURANT(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;
ALTER TABLE CONTACT_INFO
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES USER_AUTH(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;

--CONSUMER_ORDER Foreign Keys With RESTAURANT and USER_AUTH
ALTER TABLE CONSUMER_ORDER
	ADD FOREIGN KEY (RESTAURANT_ID) 
	REFERENCES RESTAURANT(ID)
	ON DELETE SET NULL DEFERRABLE CHECK;

ALTER TABLE CONSUMER_ORDER
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES USER_AUTH(ID)
	ON DELETE CASCADE DEFERRABLE CHECK;

--ORDER_ITEM Foreign Keys With FOOD_ITEM
ALTER TABLE ORDER_ITEM
	ADD FOREIGN KEY (FOOD_ITEM_ID) 
	REFERENCES FOOD_ITEM(ID)
    ON DELETE CASCADE DEFERRABLE CHECK ;
ALTER TABLE ORDER_ITEM
	ADD FOREIGN KEY (ORDER_ID) 
	REFERENCES CONSUMER_ORDER(ID)
    ON DELETE SET NULL DEFERRABLE CHECK ;

--RESTAURANT_ITEM Foreign Keys With FOOD_ITEM
ALTER TABLE RESTAURANT_ITEM
	ADD FOREIGN KEY (FOOD_ITEM_ID) 
	REFERENCES FOOD_ITEM(ID)
    ON DELETE CASCADE DEFERRABLE CHECK ;

ALTER TABLE RESTAURANT_ITEM
	ADD FOREIGN KEY (RESTAURANT_ID) 
	REFERENCES RESTAURANT(ID)
    ON DELETE CASCADE DEFERRABLE CHECK ;

ALTER TABLE RESTAURANT_ITEM
	ADD FOREIGN KEY (CART_ID)
	REFERENCES CART(ID)
    ON DELETE CASCADE DEFERRABLE CHECK ;
	

CREATE TABLE IF NOT EXISTS ROLES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID NUMBER,
    ROLE_ID NUMBER
);

ALTER TABLE USER_ROLES ADD CONSTRAINT USER_ROLES_USER_FK
    FOREIGN KEY (USER_ID) REFERENCES USER_AUTH(ID)
        ON DELETE CASCADE DEFERRABLE CHECK ;
ALTER TABLE USER_ROLES ADD CONSTRAINT USER_ROLES_ROLE_FK
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
        ON DELETE CASCADE DEFERRABLE CHECK ;

CREATE TABLE IF NOT EXISTS PRIVILEGES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLE_PRIVILEGES
(
    ROLE_ID      NUMBER,
    PRIVILEGE_ID NUMBER
);

ALTER TABLE ROLE_PRIVILEGES ADD CONSTRAINT ROLE_PRIVILEGES_PRIVILEGE_FK
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGES(ID)
        ON DELETE CASCADE DEFERRABLE CHECK ;
ALTER TABLE ROLE_PRIVILEGES ADD CONSTRAINT ROLE_PRIVILEGES_ROLE_FK
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
        ON DELETE CASCADE DEFERRABLE CHECK ;